name = "p-rer"
main = "worker.js"
compatibility_date = "2026-01-01"

[[routes]]
pattern = "devtem.org/p*"
zone_name = "devtem.org"

[[routes]]
pattern = "devtem.org/s*"
zone_name = "devtem.org"

[[routes]]
pattern = "www.devtem.org/s*"
zone_name = "devtem.org"

[[routes]]
pattern = "www.devtem.org/p*"
zone_name = "devtem.org"
